###########################
##      LOCAL MACOS      ##
###########################
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure Homebrew is installed
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Ensure 'brew services' is tapped
      homebrew_tap:
        name: homebrew/services

    - name: Install Docker Compose via cask
      homebrew_cask:
        name: docker-compose
        state: present
