###########################
##      LOCAL MACOS      ##
###########################
---
- hosts: all
  tasks:
    - name: Set global variable username
      set_fact:
        username: "romanchudov"

- import_playbook: tools.yml
- import_playbook: zsh.yml
- import_playbook: go.yml
- import_playbook: apps.yml
- import_playbook: ides.yml
