###########################
##      LOCAL MACOS      ##
###########################
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure Homebrew is installed
      command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      args:
        creates: /usr/local/bin/brew

    - name: Ensure 'brew services' is tapped
      homebrew_tap:
        name: homebrew/services

    - name: Install mc
      homebrew:
        name: mc
        state: present

    - name: Install ranger
      homebrew:
        name: ranger
        state: present

    - name: Install htop
      homebrew:
        name: htop
        state: present

    - name: Install wget
      homebrew:
        name: wget
        state: present

    - name: Install curl
      homebrew:
        name: curl
        state: present

    - name: Install coreutils
      homebrew:
        name: coreutils
        state: present

    - name: Install python3
      homebrew:
        name: python3
        state: present

    - name: Install git
      homebrew:
        name: git
        state: present

    - name: Install pre-commit
      homebrew:
        name: pre-commit
        state: present

    - name: Install Google Chrome via cask
      homebrew_cask:
        name: google-chrome
        state: present

    - name: Install Yandex Browser via cask
      homebrew_cask:
        name: yandex
        state: present

    - name: Install Yandex Disk via cask
      homebrew_cask:
        name: yandex-disk
        state: present

    - name: Install Visual Studio Code via cask
      homebrew_cask:
        name: visual-studio-code
        state: present

    - name: Install JetBrains Toolbox via cask
      homebrew_cask:
        name: jetbrains-toolbox
        state: present

    - name: Install Sublime Text via cask
      homebrew_cask:
        name: sublime-text
        state: present

    - name: Install Lens via cask
      homebrew_cask:
        name: lens
        state: present

    # - name: Install Docker via cask
    #   homebrew_cask:
    #     name: docker
    #     state: present

    - name: Install Zoom via cask
      homebrew_cask:
        name: zoom
        state: present

    - name: Install Postman via cask
      homebrew_cask:
        name: postman
        state: present
