############################
##       SETUP TOOLS      ##
############################
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Install zsh
      homebrew:
        name: zsh
        state: present

    - name: Install iterm2
      homebrew:
        name: iterm2
        state: present
